replicaCount: 1
deployFrontend: true
deployBackend: false
deployPostgres: false
deployIngress: false

namespace: dev
tag: "ac317afd5d105fd9396eb02c5a7ae0c8df76212f"
resources:
  requests:
    cpu_frontend: "500m"
    memory_frontend: "750Mi"
  limits:
    cpu_frontend: "750m"
    memory_frontend: "750Mi"

hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env:
  VITE_API_URL: "http://dev-app.myakuracy.click"
