replicaCount: 1
deployFrontend: true
deployBackend: false
deployPostgres: false
deployIngress: false

namespace: dev
tag: "b90a0384f52dadbc0d114e66d73033ca66642d5b"
resources:
  requests:
    cpu_frontend: "500m"
    memory_frontend: "750Mi"
  limits:
    cpu_frontend: "750m"
    memory_frontend: "750Mi"

hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env:
  VITE_API_URL: "http://dev-app.myakuracy.click"
